name: flutter_google_maps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Google Maps
  google_maps_flutter: ^2.1.1

   #State
  provider: ^6.0.2

  # Location Permission
  location: ^4.3.0

  # Ui Utility
  kartal: ^2.3.1

  # Core Utility
  flutter_dotenv: ^5.0.2

  # web socket library
  pusher_client: ^2.0.0

  # Json Serializing
  json_annotation: ^4.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  # Google
  json_serializable: ^6.1.4
  build_runner: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
